name: QuickLookMD
options:
  bundleIdPrefix: dev.rachel.notapeek
  deploymentTarget:
    macOS: "12.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    PRODUCT_MODULE_NAME: QuickLookMD
    DEVELOPMENT_TEAM: 5U92RP4C5J
targets:
  QuickLookMD:
    type: app-extension
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: PreviewViewController.swift
      - path: Resources/marked.min.js
        buildPhase: resources
      - path: Resources/highlight.min.js
        buildPhase: resources
      - path: Resources/preview.css
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.rachel.notapeek.quicklook
        PRODUCT_NAME: QuickLookMD
        MARKETING_VERSION: "1.0.5"
        CURRENT_PROJECT_VERSION: 7
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: QuickLookMD.entitlements
        SKIP_INSTALL: NO
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        ENABLE_APP_SANDBOX: YES
        ENABLE_USER_SELECTED_FILES: readonly
